          updated_at           |          created_at           | id |  type  | query_id |      name      | description |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    options                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
-------------------------------+-------------------------------+----+--------+----------+----------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 2020-08-13 14:44:13.130564+08 | 2020-08-13 14:44:13.130564+08 |  1 | TABLE  |        1 | Table          |             | {}
 2020-08-13 15:19:56.061242+08 | 2020-08-13 15:19:56.061242+08 |  3 | TABLE  |        2 | Table          |             | {}
 2020-08-13 15:28:08.569012+08 | 2020-08-13 15:28:08.569012+08 |  4 | TABLE  |        3 | Table          |             | {}
 2020-09-16 17:58:08.421951+08 | 2020-09-16 15:00:50.465183+08 | 17 | CHART  |        7 | 图表           |             | {"globalSeriesType": "column", "sortX": true, "legend": {"enabled": true, "placement": "auto"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "xAxis": {"type": "-", "labels": {"enabled": true}}, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {}, "valuesOptions": {}, "columnMapping": {"api_url": "x", "name": "y", "request_sample": "series"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm"}
 2020-08-13 15:32:33.02728+08  | 2020-08-13 15:31:06.497+08    |  5 | CHART  |        3 | Chart          |             | {"globalSeriesType": "pie", "sortX": true, "legend": {"enabled": true, "placement": "auto"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "xAxis": {"type": "-", "labels": {"enabled": true}}, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {}, "valuesOptions": {}, "columnMapping": {"id": "x", "x_brand_code": "y"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": true, "dateTimeFormat": "DD/MM/YY HH:mm"}
 2020-09-10 10:32:20.382425+08 | 2020-08-13 15:39:46.475+08    |  7 | CHART  |        4 | Chart          |             | {"globalSeriesType": "column", "sortX": true, "legend": {"enabled": true, "placement": "auto"}, "yAxis": [{"type": "linear", "rangeMin": 1, "rangeMax": 20}, {"type": "category", "opposite": true}], "xAxis": {"type": "-", "labels": {"enabled": true}}, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}, "percentValues": false}, "seriesOptions": {"count": {"yAxis": 0, "type": "column", "color": "#A55F2A", "name": "count"}}, "valuesOptions": {"false": {"color": "#FB8D3D"}, "true": {"color": "#B554FF"}}, "columnMapping": {"active": "x", "count": "y"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": false, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm", "colorScheme": "Custom...", "heatMinColor": "#3BD973", "heatMaxColor": "#E92828", "reverseX": true}
 2020-09-10 10:33:33.63714+08  | 2020-08-20 11:52:28.936+08    | 10 | FUNNEL |        4 | 漏斗图         |             | {"stepCol": {"colName": "active", "displayAs": "\u5c42\u7ea7"}, "valueCol": {"colName": "active", "displayAs": "\u503c"}, "autoSort": true, "sortKeyCol": {"colName": "active", "reverse": true}, "itemsLimit": 100, "percentValuesRange": {"min": 0.01, "max": 1000}, "numberFormat": "0,0[.]00", "percentFormat": "0[.]00%"}
 2020-09-18 17:37:31.643279+08 | 2020-09-16 14:52:22.167535+08 | 16 | TABLE  |        7 | Table          |             | {}
 2020-09-16 14:36:08.38408+08  | 2020-08-13 15:37:48.666593+08 |  6 | TABLE  |        4 | Table          |             | {}
 2020-08-25 15:30:41.555109+08 | 2020-08-20 13:57:35.773994+08 | 11 | MAP    |        4 | 地图（标记图） |             | {"latColName": "active", "lonColName": "lon", "classify": null, "groups": {}, "mapTileUrl": "//{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png", "clusterMarkers": true, "customizeMarkers": true, "iconShape": "marker", "iconFont": "circle", "foregroundColor": "#FF7DE3", "backgroundColor": "#356AFF", "borderColor": "#356AFF", "bounds": null, "tooltip": {"enabled": false, "template": ""}, "popup": {"enabled": true, "template": ""}}
 2020-09-02 15:37:28.991797+08 | 2020-09-02 15:37:28.991797+08 | 12 | TABLE  |        5 | Table          |             | {}
 2020-09-02 15:53:34.529337+08 | 2020-09-02 15:53:34.529337+08 | 13 | CHART  |        5 | 图表           |             | {"globalSeriesType": "column", "sortX": true, "legend": {"enabled": false, "placement": "auto"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "xAxis": {"type": "-", "labels": {"enabled": true}}, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {}, "valuesOptions": {}, "columnMapping": {"login": "x", "id": "y"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm"}
 2020-09-03 10:20:35.994131+08 | 2020-09-03 10:20:35.994131+08 | 14 | TABLE  |        6 | Table          |             | {}
 2020-09-16 15:01:24.736562+08 | 2020-09-07 10:21:32.714436+08 | 15 | CHART  |        4 | 图表           |             | {"globalSeriesType": "line", "sortX": true, "legend": {"enabled": true, "placement": "auto"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "xAxis": {"type": "-", "labels": {"enabled": true}}, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {"count": {"color": "#C63FA9"}}, "valuesOptions": {}, "columnMapping": {"active": "x", "count": "y"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm"}
(14 rows)

